INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY) VALUES ('Joe', 'Bloggs', 100.5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY) VALUES ('Josh', 'Doug', 90.5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY) VALUES ('Roz', 'Brocc', 80.5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY) VALUES ('Uzi', 'Man', 70.5);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, SALARY) VALUES ('Mo', 'Kun', 60.5);
